import { User, Vehicle, Dock, PurchaseOrder, Booking, OperationalSettings, OperationalHoliday } from '../types';

export const INITIAL_SETTINGS: OperationalSettings = {
  factoryOpenTime: '08:00',
  maxArrivalBookingTime: '19:00',
  factoryCloseTime: '23:00',
  slotIntervalMinutes: 30,
};

export const INITIAL_HOLIDAYS: OperationalHoliday[] = [
  {
    id: 'hol-1',
    date: '2026-05-01',
    description: 'Hari Buruh Internasional (Plant Closed)',
    isLocked: true,
  },
  {
    id: 'hol-2',
    date: '2026-08-17',
    description: 'Hari Kemerdekaan Republik Indonesia ke-81',
    isLocked: true,
  },
  {
    id: 'hol-3',
    date: '2026-12-25',
    description: 'Hari Raya Natal & Cuti Bersama Akhir Tahun',
    isLocked: true,
  },
  {
    id: 'hol-4',
    date: '2026-09-15',
    description: 'Annual Preventive Maintenance Mesin & Crane Dock',
    isLocked: false,
  },
];

export const INITIAL_VEHICLES: Vehicle[] = [
  {
    id: 'veh-cde',
    name: 'Engkel (CDE)',
    vehicleName: 'Engkel (CDE)',
    code: 'CDE',
    durationMinutes: 60,
    defaultDurationMinutes: 60,
    allowedDockTypes: ['GENERAL'],
    description: 'Armada kapasitas 2-3 Ton, muatan ringan/karton',
    isActive: true,
  },
  {
    id: 'veh-cdd',
    name: 'Double Engkel (CDD)',
    vehicleName: 'Double Engkel (CDD)',
    code: 'CDD',
    durationMinutes: 90,
    defaultDurationMinutes: 90,
    allowedDockTypes: ['GENERAL'],
    description: 'Armada kapasitas 4-5 Ton, 6 roda',
    isActive: true,
  },
  {
    id: 'veh-fuso',
    name: 'Fuso',
    vehicleName: 'Fuso',
    code: 'FUSO',
    durationMinutes: 120,
    defaultDurationMinutes: 120,
    allowedDockTypes: ['GENERAL'],
    description: 'Armada berat kapasitas 7-10 Ton',
    isActive: true,
  },
  {
    id: 'veh-wb10',
    name: 'Wingbox 10 Ton',
    vehicleName: 'Wingbox 10 Ton',
    code: 'WB10',
    durationMinutes: 120,
    defaultDurationMinutes: 120,
    allowedDockTypes: ['GENERAL'],
    description: 'Truk box hidrolik samping, muat pallet cepat',
    isActive: true,
  },
  {
    id: 'veh-wb20',
    name: 'Wingbox 20 Ton',
    vehicleName: 'Wingbox 20 Ton',
    code: 'WB20',
    durationMinutes: 180,
    defaultDurationMinutes: 180,
    allowedDockTypes: ['GENERAL'],
    description: 'Heavy duty tronton wingbox 20 Ton',
    isActive: true,
  },
  {
    id: 'veh-isotank',
    name: 'Isotank / Tangki Cair',
    vehicleName: 'Isotank / Tangki Cair',
    code: 'ISOTANK',
    durationMinutes: 180,
    defaultDurationMinutes: 180,
    allowedDockTypes: ['LIQUID', 'LIQUID_ISOTANK'],
    description: 'Khusus bahan kimia/cairan, butuh pipa & pompa dock tangki',
    isActive: true,
  },
  {
    id: 'veh-container',
    name: 'Kontainer 20/40 ft',
    vehicleName: 'Kontainer 20/40 ft',
    code: 'CONT',
    durationMinutes: 240,
    defaultDurationMinutes: 240,
    allowedDockTypes: ['CONTAINER', 'GENERAL'],
    description: 'Peti kemas ekspor/impor 20ft atau 40ft',
    isActive: true,
  },
];

export const INITIAL_DOCKS: Dock[] = [
  {
    id: 'dock-1',
    name: 'Dock 1 (General Bay A)',
    dockName: 'Dock 01 (General Bay A)',
    dockType: 'GENERAL',
    maxTonnage: 25,
    notes: 'Hydraulic dock leveller, cocok untuk CDE/CDD/Fuso/Wingbox',
    isActive: true,
  },
  {
    id: 'dock-2',
    name: 'Dock 2 (General Bay B)',
    dockName: 'Dock 02 (General Bay B)',
    dockType: 'GENERAL',
    maxTonnage: 25,
    notes: 'Dekat area racking bahan baku kering',
    isActive: true,
  },
  {
    id: 'dock-3',
    name: 'Dock 3 (Fast Pallet Bay)',
    dockName: 'Dock 03 (Fast Pallet Bay)',
    dockType: 'GENERAL',
    maxTonnage: 30,
    notes: 'Double forklift access, optimal untuk Wingbox',
    isActive: true,
  },
  {
    id: 'dock-4',
    name: 'Dock 4 (Bay Tangki / Isotank)',
    dockName: 'Dock 04 (Bay Tangki / Isotank)',
    dockType: 'LIQUID',
    maxTonnage: 35,
    notes: 'Dilengkapi manifold piping transfer kimia & scrubber udara',
    isActive: true,
  },
  {
    id: 'dock-5',
    name: 'Dock 5 (Container High Bay)',
    dockName: 'Dock 05 (Container High Bay)',
    dockType: 'CONTAINER',
    maxTonnage: 45,
    notes: 'Heavy duty leveller untuk chassis kontainer 20/40 ft',
    isActive: true,
  },
];

export const INITIAL_USERS: User[] = [
  {
    id: 'user-admin',
    name: 'Budi Santoso, ST',
    email: 'admin.logistik@pabrik.co.id',
    role: 'ADMIN',
    department: 'Plant Operations & IT',
  },
  {
    id: 'user-purchasing',
    name: 'Rina Wijaya, SE',
    email: 'purchasing@pabrik.co.id',
    role: 'PURCHASING',
    department: 'Procurement Division',
  },
  {
    id: 'user-ppic',
    name: 'Hendra Pratama',
    email: 'ppic.planning@pabrik.co.id',
    role: 'PPIC',
    department: 'Production Planning & Control',
  },
  {
    id: 'user-supplier-1',
    name: 'Joko Susilo (PT Sumber Logistik Prima)',
    email: 'dispatch@sumberlogistik.com',
    role: 'SUPPLIER',
    supplierName: 'PT Sumber Logistik Prima',
  },
  {
    id: 'user-supplier-2',
    name: 'Ahmad Dahlan (PT Kimia Indah Perkasa)',
    email: 'logistik@kimiaindah.com',
    role: 'SUPPLIER',
    supplierName: 'PT Kimia Indah Perkasa',
  },
  {
    id: 'user-warehouse',
    name: 'Agus Sutrisno (Head of Warehouse)',
    email: 'gudang.receiving@pabrik.co.id',
    role: 'WAREHOUSE',
    department: 'Warehouse Receiving & Gate Control',
  },
];

// Helper to generate current date in YYYY-MM-DD
const today = new Date();
export const TODAY_STR = today.toISOString().split('T')[0];

export const getOffsetDate = (offsetDays: number) => {
  const d = new Date(today);
  d.setDate(today.getDate() + offsetDays);
  return d.toISOString().split('T')[0];
};

export const TOMORROW_STR = getOffsetDate(1);
export const YESTERDAY_STR = getOffsetDate(-1);
export const DAY_MINUS_1_STR = YESTERDAY_STR;
export const DAY_MINUS_2_STR = getOffsetDate(-2);
export const DAY_MINUS_3_STR = getOffsetDate(-3);
export const DAY_PLUS_2_STR = getOffsetDate(2);
export const DAY_PLUS_3_STR = getOffsetDate(3);

export const INITIAL_POS: PurchaseOrder[] = [
  {
    id: 'po-101',
    poNumber: 'PO-2026-08101',
    supplierName: 'PT Sumber Logistik Prima',
    supplierEmail: 'dispatch@sumberlogistik.com',
    supplierPhone: '0812-8899-7711',
    itemDescription: 'Cardboard Box Packaging 500x400x300mm',
    quantity: 4500,
    qty: 4500,
    unit: 'PCS',
    priority: 'URGENT',
    status: 'BOOKED',
    etaStartDate: DAY_MINUS_2_STR,
    etaEndDate: TODAY_STR,
    ppicEtaDateStart: DAY_MINUS_2_STR,
    ppicEtaDateEnd: TODAY_STR,
    ppicNotes: 'Dibutuhkan segera untuk line packaging 1 shift malam',
    createdBy: 'Rina Wijaya (Purchasing)',
    reviewedBy: 'Hendra Pratama (PPIC)',
    createdAt: `${TODAY_STR}T07:15:00`,
    updatedAt: `${TODAY_STR}T07:20:00`,
  },
  {
    id: 'po-102',
    poNumber: 'PO-2026-08102',
    supplierName: 'PT Kimia Indah Perkasa',
    supplierEmail: 'logistik@kimiaindah.com',
    supplierPhone: '0813-4455-6677',
    itemDescription: 'Liquid Solvents Poly-Grade X-80',
    quantity: 18000,
    qty: 18000,
    unit: 'LITER',
    priority: 'NORMAL',
    status: 'BOOKED',
    etaStartDate: DAY_MINUS_1_STR,
    etaEndDate: TODAY_STR,
    ppicEtaDateStart: DAY_MINUS_1_STR,
    ppicEtaDateEnd: TODAY_STR,
    ppicNotes: 'Wajib masuk Dock 04 Tangki, sampling QC terlebih dahulu',
    createdBy: 'Rina Wijaya (Purchasing)',
    reviewedBy: 'Hendra Pratama (PPIC)',
    createdAt: `${TODAY_STR}T07:30:00`,
    updatedAt: `${TODAY_STR}T07:35:00`,
  },
  {
    id: 'po-103',
    poNumber: 'PO-2026-08103',
    supplierName: 'PT Steel Indo Sukses',
    supplierEmail: 'sales@steelindo.co.id',
    supplierPhone: '0811-2233-4455',
    itemDescription: 'Cold Rolled Steel Coil Sheet 1.2mm',
    quantity: 24,
    qty: 24,
    unit: 'COIL',
    priority: 'URGENT',
    status: 'BOOKED',
    etaStartDate: TODAY_STR,
    etaEndDate: TOMORROW_STR,
    ppicEtaDateStart: TODAY_STR,
    ppicEtaDateEnd: TOMORROW_STR,
    ppicNotes: 'Gunakan Dock Kontainer atau Bay 03 dengan overhead crane',
    createdBy: 'Rina Wijaya (Purchasing)',
    reviewedBy: 'Hendra Pratama (PPIC)',
    createdAt: `${TODAY_STR}T08:00:00`,
    updatedAt: `${TODAY_STR}T08:10:00`,
  },
  {
    id: 'po-104',
    poNumber: 'PO-2026-08104',
    supplierName: 'PT Sumber Logistik Prima',
    supplierEmail: 'dispatch@sumberlogistik.com',
    supplierPhone: '0812-8899-7711',
    itemDescription: 'Pallet Kayu Standar ISPM-15 120x100cm',
    quantity: 400,
    qty: 400,
    unit: 'PALLET',
    priority: 'NORMAL',
    status: 'BOOKED',
    etaStartDate: TODAY_STR,
    etaEndDate: TODAY_STR,
    ppicEtaDateStart: TODAY_STR,
    ppicEtaDateEnd: TODAY_STR,
    ppicNotes: 'Pengiriman via Wingbox 10 Ton',
    createdBy: 'Rina Wijaya (Purchasing)',
    reviewedBy: 'Hendra Pratama (PPIC)',
    createdAt: `${TODAY_STR}T08:20:00`,
    updatedAt: `${TODAY_STR}T08:25:00`,
  },
  {
    id: 'po-105',
    poNumber: 'PO-2026-08105',
    supplierName: 'PT Plastik Raya Sejahtera',
    supplierEmail: 'orders@plastikraya.com',
    supplierPhone: '0815-9988-7766',
    itemDescription: 'Polypropylene Resin Granules (Bags @25kg)',
    quantity: 1200,
    qty: 1200,
    unit: 'BAG',
    priority: 'NORMAL',
    status: 'READY_FOR_BOOKING',
    etaStartDate: TODAY_STR,
    etaEndDate: DAY_PLUS_2_STR,
    ppicEtaDateStart: TODAY_STR,
    ppicEtaDateEnd: DAY_PLUS_2_STR,
    ppicNotes: 'Sudah di-approve oleh PPIC. Silakan supplier ambil slot delivery.',
    createdBy: 'Rina Wijaya (Purchasing)',
    reviewedBy: 'Hendra Pratama (PPIC)',
    createdAt: `${TODAY_STR}T08:45:00`,
    updatedAt: `${TODAY_STR}T09:00:00`,
  },
  {
    id: 'po-106',
    poNumber: 'PO-2026-08106',
    supplierName: 'PT Aneka Kimia Sentosa',
    supplierEmail: 'supply@anekakimia.co.id',
    supplierPhone: '0818-1234-5678',
    itemDescription: 'Caustic Soda Flakes 99% Technical Grade',
    quantity: 500,
    qty: 500,
    unit: 'DRUM',
    priority: 'URGENT',
    status: 'READY_FOR_BOOKING',
    etaStartDate: TOMORROW_STR,
    etaEndDate: DAY_PLUS_3_STR,
    ppicEtaDateStart: TOMORROW_STR,
    ppicEtaDateEnd: DAY_PLUS_3_STR,
    ppicNotes: 'Kebutuhan urgent water treatment plant. Siap booking slot pengiriman besok.',
    createdBy: 'Rina Wijaya (Purchasing)',
    reviewedBy: 'Hendra Pratama (PPIC)',
    createdAt: `${TODAY_STR}T09:10:00`,
    updatedAt: `${TODAY_STR}T09:20:00`,
  },
  {
    id: 'po-107',
    poNumber: 'PO-2026-08107',
    supplierName: 'PT Cemerlang Paper Mills',
    supplierEmail: 'delivery@cemerlangpaper.com',
    supplierPhone: '0819-7766-5544',
    itemDescription: 'Kraft Liner Board Paper 150 GSM',
    quantity: 15,
    qty: 15,
    unit: 'TON',
    priority: 'URGENT',
    status: 'WAITING_PPIC_REVIEW',
    ppicNotes: 'Prioritas tinggi untuk produksi kemasan karton batch 40',
    createdBy: 'Rina Wijaya (Purchasing)',
    createdAt: `${TODAY_STR}T09:40:00`,
    updatedAt: `${TODAY_STR}T09:40:00`,
  },
  {
    id: 'po-108',
    poNumber: 'PO-2026-08108',
    supplierName: 'PT Mitra Baja Nusantara',
    supplierEmail: 'order@mitrabaja.co.id',
    supplierPhone: '0812-3344-5566',
    itemDescription: 'H-Beam Carbon Structural Steel 200x200',
    quantity: 18,
    qty: 18,
    unit: 'TON',
    priority: 'NORMAL',
    status: 'WAITING_PPIC_REVIEW',
    createdBy: 'Rina Wijaya (Purchasing)',
    createdAt: `${TODAY_STR}T10:15:00`,
    updatedAt: `${TODAY_STR}T10:15:00`,
  },
  {
    id: 'po-109',
    poNumber: 'PO-2026-08109',
    supplierName: 'PT Indofood Agrosari',
    supplierEmail: 'sales@indofoodagro.com',
    supplierPhone: '0817-6655-4433',
    itemDescription: 'Refined Bleached Palm Oil (RBDPO) Bulk',
    quantity: 22,
    qty: 22,
    unit: 'TON',
    priority: 'NORMAL',
    status: 'DRAFT',
    createdBy: 'Rina Wijaya (Purchasing)',
    createdAt: `${TODAY_STR}T10:50:00`,
    updatedAt: `${TODAY_STR}T10:50:00`,
  },
];

export const INITIAL_BOOKINGS: Booking[] = [
  // --- TODAY BOOKINGS ---
  {
    id: 'bk-01',
    bookingCode: `SLOT-${TODAY_STR.replace(/-/g, '')}-D1-01`,
    poId: 'po-101',
    poNumber: 'PO-2026-08101',
    supplierName: 'PT Sumber Logistik Prima',
    itemDescription: 'Cardboard Box Packaging 500x400x300mm',
    qty: 4500,
    unit: 'PCS',
    dockId: 'dock-1',
    dockName: 'Dock 01 (General Bay A)',
    vehicleId: 'veh-cdd',
    vehicleName: 'Double Engkel (CDD)',
    vehicleCode: 'CDD',
    driverName: 'Suryanto W.',
    driverPhone: '0812-8899-7711',
    licensePlate: 'B 9421 UQ',
    startTime: `${TODAY_STR}T08:30:00`,
    endTime: `${TODAY_STR}T10:00:00`,
    durationMinutes: 90,
    actualGateIn: `${TODAY_STR}T08:22:00`,
    actualStartUnload: `${TODAY_STR}T08:35:00`,
    actualFinishUnload: `${TODAY_STR}T09:50:00`,
    actualGateOut: `${TODAY_STR}T10:02:00`,
    status: 'DONE',
    remarks: 'Bongkar selesai lancar sesuai SOP, 100% item verified.',
    createdAt: `${TODAY_STR}T07:20:00`,
  },
  {
    id: 'bk-01b',
    bookingCode: `SLOT-${TODAY_STR.replace(/-/g, '')}-D1-02`,
    poId: 'po-101',
    poNumber: 'PO-2026-08101',
    supplierName: 'PT Sumber Logistik Prima',
    itemDescription: 'Cardboard Box Outer Pallet',
    qty: 2000,
    unit: 'PCS',
    dockId: 'dock-1',
    dockName: 'Dock 01 (General Bay A)',
    vehicleId: 'veh-cde',
    vehicleName: 'Engkel (CDE)',
    vehicleCode: 'CDE',
    driverName: 'Eko Prasetyo',
    driverPhone: '0812-3344-5566',
    licensePlate: 'B 9122 XY',
    startTime: `${TODAY_STR}T11:00:00`,
    endTime: `${TODAY_STR}T12:00:00`,
    durationMinutes: 60,
    status: 'BOOKED',
    remarks: 'Pengiriman batch 2',
    createdAt: `${TODAY_STR}T08:00:00`,
  },
  {
    id: 'bk-02',
    bookingCode: `SLOT-${TODAY_STR.replace(/-/g, '')}-D4-01`,
    poId: 'po-102',
    poNumber: 'PO-2026-08102',
    supplierName: 'PT Kimia Indah Perkasa',
    itemDescription: 'Liquid Solvents Poly-Grade X-80',
    qty: 18000,
    unit: 'LITER',
    dockId: 'dock-4',
    dockName: 'Dock 04 (Bay Tangki / Isotank)',
    vehicleId: 'veh-isotank',
    vehicleName: 'Isotank / Tangki Cair',
    vehicleCode: 'ISOTANK',
    driverName: 'Bambang Irawan',
    driverPhone: '0813-1122-3344',
    licensePlate: 'B 9088 TKL',
    startTime: `${TODAY_STR}T09:30:00`,
    endTime: `${TODAY_STR}T12:30:00`,
    durationMinutes: 180,
    actualGateIn: `${TODAY_STR}T09:20:00`,
    actualStartUnload: `${TODAY_STR}T09:40:00`,
    status: 'UNLOADING',
    remarks: 'Sedang proses transfer pompa ke tangki penampungan T-04 (60% completed)',
    createdAt: `${TODAY_STR}T07:45:00`,
  },
  {
    id: 'bk-02b',
    bookingCode: `SLOT-${TODAY_STR.replace(/-/g, '')}-D4-02`,
    poId: 'po-102',
    poNumber: 'PO-2026-08102',
    supplierName: 'PT Kimia Indah Perkasa',
    itemDescription: 'Solvent Grade B (Isotank 2)',
    qty: 15000,
    unit: 'LITER',
    dockId: 'dock-4',
    dockName: 'Dock 04 (Bay Tangki / Isotank)',
    vehicleId: 'veh-isotank',
    vehicleName: 'Isotank / Tangki Cair',
    vehicleCode: 'ISOTANK',
    driverName: 'Rudi Hartono',
    driverPhone: '0813-9988-1122',
    licensePlate: 'B 9301 TKM',
    startTime: `${TODAY_STR}T14:00:00`,
    endTime: `${TODAY_STR}T17:00:00`,
    durationMinutes: 180,
    status: 'BOOKED',
    remarks: 'Transfer tangki penampungan T-05',
    createdAt: `${TODAY_STR}T08:10:00`,
  },
  {
    id: 'bk-03',
    bookingCode: `SLOT-${TODAY_STR.replace(/-/g, '')}-D5-01`,
    poId: 'po-103',
    poNumber: 'PO-2026-08103',
    supplierName: 'PT Steel Indo Sukses',
    itemDescription: 'Cold Rolled Steel Coil Sheet 1.2mm',
    qty: 24,
    unit: 'COIL',
    dockId: 'dock-5',
    dockName: 'Dock 05 (Container High Bay)',
    vehicleId: 'veh-container',
    vehicleName: 'Kontainer 20/40 ft',
    vehicleCode: 'CONT',
    driverName: 'Wahyu Hidayat',
    driverPhone: '0857-4455-6677',
    licensePlate: 'B 9912 CTX',
    startTime: `${TODAY_STR}T13:00:00`,
    endTime: `${TODAY_STR}T17:00:00`,
    durationMinutes: 240,
    actualGateIn: `${TODAY_STR}T12:45:00`,
    status: 'ARRIVED',
    remarks: 'Truk kontainer sudah di gate, menunggu dock leveller siap jam 13:00',
    createdAt: `${TODAY_STR}T08:15:00`,
  },
  {
    id: 'bk-04',
    bookingCode: `SLOT-${TODAY_STR.replace(/-/g, '')}-D3-01`,
    poId: 'po-104',
    poNumber: 'PO-2026-08104',
    supplierName: 'PT Sumber Logistik Prima',
    itemDescription: 'Pallet Kayu Standar ISPM-15 120x100cm',
    qty: 400,
    unit: 'PALLET',
    dockId: 'dock-3',
    dockName: 'Dock 03 (Fast Pallet Bay)',
    vehicleId: 'veh-wb10',
    vehicleName: 'Wingbox 10 Ton',
    vehicleCode: 'WB10',
    driverName: 'Denny Kurniawan',
    driverPhone: '0818-7788-9900',
    licensePlate: 'D 8831 AA',
    startTime: `${TODAY_STR}T14:30:00`,
    endTime: `${TODAY_STR}T16:30:00`,
    durationMinutes: 120,
    status: 'BOOKED',
    remarks: 'Estimasi kedatangan pukul 14:15 WIB',
    createdAt: `${TODAY_STR}T08:35:00`,
  },

  // --- YESTERDAY BOOKINGS (DAY -1) ---
  {
    id: 'bk-y01',
    bookingCode: `SLOT-${YESTERDAY_STR.replace(/-/g, '')}-D4-01`,
    poId: 'po-102',
    poNumber: 'PO-2026-08102',
    supplierName: 'PT Kimia Indah Perkasa',
    itemDescription: 'Liquid Solvents Bulk',
    qty: 18000,
    unit: 'LITER',
    dockId: 'dock-4',
    dockName: 'Dock 04 (Bay Tangki / Isotank)',
    vehicleId: 'veh-isotank',
    vehicleName: 'Isotank / Tangki Cair',
    vehicleCode: 'ISOTANK',
    driverName: 'Bambang Irawan',
    driverPhone: '0813-1122-3344',
    licensePlate: 'B 9088 TKL',
    startTime: `${YESTERDAY_STR}T08:30:00`,
    endTime: `${YESTERDAY_STR}T11:30:00`,
    durationMinutes: 180,
    actualGateIn: `${YESTERDAY_STR}T08:15:00`,
    actualStartUnload: `${YESTERDAY_STR}T08:35:00`,
    actualFinishUnload: `${YESTERDAY_STR}T11:20:00`,
    actualGateOut: `${YESTERDAY_STR}T11:35:00`,
    status: 'DONE',
    remarks: 'Bongkar tangki selesai 100%',
    createdAt: `${YESTERDAY_STR}T07:00:00`,
  },
  {
    id: 'bk-y02',
    bookingCode: `SLOT-${YESTERDAY_STR.replace(/-/g, '')}-D4-02`,
    poId: 'po-102',
    poNumber: 'PO-2026-08102',
    supplierName: 'PT Kimia Indah Perkasa',
    itemDescription: 'Methanol Pure Grade',
    qty: 16000,
    unit: 'LITER',
    dockId: 'dock-4',
    dockName: 'Dock 04 (Bay Tangki / Isotank)',
    vehicleId: 'veh-isotank',
    vehicleName: 'Isotank / Tangki Cair',
    vehicleCode: 'ISOTANK',
    driverName: 'Sugeng Riyadi',
    driverPhone: '0813-4455-8899',
    licensePlate: 'B 9012 TKA',
    startTime: `${YESTERDAY_STR}T12:30:00`,
    endTime: `${YESTERDAY_STR}T15:30:00`,
    durationMinutes: 180,
    status: 'DONE',
    remarks: 'Selesai',
    createdAt: `${YESTERDAY_STR}T07:30:00`,
  },
  {
    id: 'bk-y03',
    bookingCode: `SLOT-${YESTERDAY_STR.replace(/-/g, '')}-D1-01`,
    poId: 'po-101',
    poNumber: 'PO-2026-08101',
    supplierName: 'PT Sumber Logistik Prima',
    itemDescription: 'Cardboard Box Packaging',
    qty: 4000,
    unit: 'PCS',
    dockId: 'dock-1',
    dockName: 'Dock 01 (General Bay A)',
    vehicleId: 'veh-fuso',
    vehicleName: 'Fuso',
    vehicleCode: 'FUSO',
    driverName: 'Dedi Mulyadi',
    driverPhone: '0812-7788-9900',
    licensePlate: 'B 9772 CD',
    startTime: `${YESTERDAY_STR}T09:00:00`,
    endTime: `${YESTERDAY_STR}T11:00:00`,
    durationMinutes: 120,
    status: 'DONE',
    remarks: 'Selesai',
    createdAt: `${YESTERDAY_STR}T07:15:00`,
  },
  {
    id: 'bk-y04',
    bookingCode: `SLOT-${YESTERDAY_STR.replace(/-/g, '')}-D2-01`,
    poId: 'po-105',
    poNumber: 'PO-2026-08105',
    supplierName: 'PT Plastik Raya Sejahtera',
    itemDescription: 'Polypropylene Granules',
    qty: 800,
    unit: 'BAG',
    dockId: 'dock-2',
    dockName: 'Dock 02 (General Bay B)',
    vehicleId: 'veh-cdd',
    vehicleName: 'Double Engkel (CDD)',
    vehicleCode: 'CDD',
    driverName: 'Agus Salim',
    driverPhone: '0852-1122-4455',
    licensePlate: 'B 9382 UQ',
    startTime: `${YESTERDAY_STR}T13:00:00`,
    endTime: `${YESTERDAY_STR}T14:30:00`,
    durationMinutes: 90,
    status: 'DONE',
    remarks: 'Selesai',
    createdAt: `${YESTERDAY_STR}T08:00:00`,
  },
  {
    id: 'bk-y05',
    bookingCode: `SLOT-${YESTERDAY_STR.replace(/-/g, '')}-D3-01`,
    poId: 'po-104',
    poNumber: 'PO-2026-08104',
    supplierName: 'PT Sumber Logistik Prima',
    itemDescription: 'Pallet Kayu ISPM-15',
    qty: 400,
    unit: 'PALLET',
    dockId: 'dock-3',
    dockName: 'Dock 03 (Fast Pallet Bay)',
    vehicleId: 'veh-wb20',
    vehicleName: 'Wingbox 20 Ton',
    vehicleCode: 'WB20',
    driverName: 'Heri Kurnia',
    driverPhone: '0817-2233-4455',
    licensePlate: 'B 9555 WB',
    startTime: `${YESTERDAY_STR}T14:00:00`,
    endTime: `${YESTERDAY_STR}T17:00:00`,
    durationMinutes: 180,
    status: 'DONE',
    remarks: 'Selesai',
    createdAt: `${YESTERDAY_STR}T08:30:00`,
  },

  // --- DAY -2 BOOKINGS ---
  {
    id: 'bk-m2-01',
    bookingCode: `SLOT-${DAY_MINUS_2_STR.replace(/-/g, '')}-D5-01`,
    poId: 'po-103',
    poNumber: 'PO-2026-08103',
    supplierName: 'PT Steel Indo Sukses',
    itemDescription: 'Cold Rolled Steel Coil Sheet',
    qty: 24,
    unit: 'COIL',
    dockId: 'dock-5',
    dockName: 'Dock 05 (Container High Bay)',
    vehicleId: 'veh-container',
    vehicleName: 'Kontainer 20/40 ft',
    vehicleCode: 'CONT',
    driverName: 'Wahyu Hidayat',
    driverPhone: '0857-4455-6677',
    licensePlate: 'B 9912 CTX',
    startTime: `${DAY_MINUS_2_STR}T09:00:00`,
    endTime: `${DAY_MINUS_2_STR}T13:00:00`,
    durationMinutes: 240,
    status: 'DONE',
    remarks: 'Selesai bongkar kontainer',
    createdAt: `${DAY_MINUS_2_STR}T07:00:00`,
  },
  {
    id: 'bk-m2-02',
    bookingCode: `SLOT-${DAY_MINUS_2_STR.replace(/-/g, '')}-D4-01`,
    poId: 'po-102',
    poNumber: 'PO-2026-08102',
    supplierName: 'PT Kimia Indah Perkasa',
    itemDescription: 'Liquid Chemical X-80',
    qty: 18000,
    unit: 'LITER',
    dockId: 'dock-4',
    dockName: 'Dock 04 (Bay Tangki / Isotank)',
    vehicleId: 'veh-isotank',
    vehicleName: 'Isotank / Tangki Cair',
    vehicleCode: 'ISOTANK',
    driverName: 'Bambang Irawan',
    driverPhone: '0813-1122-3344',
    licensePlate: 'B 9088 TKL',
    startTime: `${DAY_MINUS_2_STR}T10:00:00`,
    endTime: `${DAY_MINUS_2_STR}T13:00:00`,
    durationMinutes: 180,
    status: 'DONE',
    remarks: 'Selesai',
    createdAt: `${DAY_MINUS_2_STR}T07:15:00`,
  },
  {
    id: 'bk-m2-03',
    bookingCode: `SLOT-${DAY_MINUS_2_STR.replace(/-/g, '')}-D3-01`,
    poId: 'po-104',
    poNumber: 'PO-2026-08104',
    supplierName: 'PT Sumber Logistik Prima',
    itemDescription: 'Pallet Kayu',
    qty: 300,
    unit: 'PALLET',
    dockId: 'dock-3',
    dockName: 'Dock 03 (Fast Pallet Bay)',
    vehicleId: 'veh-wb10',
    vehicleName: 'Wingbox 10 Ton',
    vehicleCode: 'WB10',
    driverName: 'Denny Kurniawan',
    driverPhone: '0818-7788-9900',
    licensePlate: 'D 8831 AA',
    startTime: `${DAY_MINUS_2_STR}T13:30:00`,
    endTime: `${DAY_MINUS_2_STR}T15:30:00`,
    durationMinutes: 120,
    status: 'DONE',
    remarks: 'Selesai',
    createdAt: `${DAY_MINUS_2_STR}T08:00:00`,
  },
  {
    id: 'bk-m2-04',
    bookingCode: `SLOT-${DAY_MINUS_2_STR.replace(/-/g, '')}-D1-01`,
    poId: 'po-101',
    poNumber: 'PO-2026-08101',
    supplierName: 'PT Sumber Logistik Prima',
    itemDescription: 'Corrugated Box',
    qty: 3500,
    unit: 'PCS',
    dockId: 'dock-1',
    dockName: 'Dock 01 (General Bay A)',
    vehicleId: 'veh-cdd',
    vehicleName: 'Double Engkel (CDD)',
    vehicleCode: 'CDD',
    driverName: 'Suryanto W.',
    driverPhone: '0812-8899-7711',
    licensePlate: 'B 9421 UQ',
    startTime: `${DAY_MINUS_2_STR}T15:00:00`,
    endTime: `${DAY_MINUS_2_STR}T16:30:00`,
    durationMinutes: 90,
    status: 'DONE',
    remarks: 'Selesai',
    createdAt: `${DAY_MINUS_2_STR}T08:30:00`,
  },

  // --- DAY -3 BOOKINGS ---
  {
    id: 'bk-m3-01',
    bookingCode: `SLOT-${DAY_MINUS_3_STR.replace(/-/g, '')}-D4-01`,
    poId: 'po-102',
    poNumber: 'PO-2026-08102',
    supplierName: 'PT Kimia Indah Perkasa',
    itemDescription: 'Liquid Solvents',
    qty: 18000,
    unit: 'LITER',
    dockId: 'dock-4',
    dockName: 'Dock 04 (Bay Tangki / Isotank)',
    vehicleId: 'veh-isotank',
    vehicleName: 'Isotank / Tangki Cair',
    vehicleCode: 'ISOTANK',
    driverName: 'Bambang Irawan',
    driverPhone: '0813-1122-3344',
    licensePlate: 'B 9088 TKL',
    startTime: `${DAY_MINUS_3_STR}T09:00:00`,
    endTime: `${DAY_MINUS_3_STR}T12:00:00`,
    durationMinutes: 180,
    status: 'DONE',
    remarks: 'Selesai',
    createdAt: `${DAY_MINUS_3_STR}T07:00:00`,
  },
  {
    id: 'bk-m3-02',
    bookingCode: `SLOT-${DAY_MINUS_3_STR.replace(/-/g, '')}-D4-02`,
    poId: 'po-102',
    poNumber: 'PO-2026-08102',
    supplierName: 'PT Kimia Indah Perkasa',
    itemDescription: 'Organic Acid Transfer',
    qty: 15000,
    unit: 'LITER',
    dockId: 'dock-4',
    dockName: 'Dock 04 (Bay Tangki / Isotank)',
    vehicleId: 'veh-isotank',
    vehicleName: 'Isotank / Tangki Cair',
    vehicleCode: 'ISOTANK',
    driverName: 'Ahmad Dahlan',
    driverPhone: '0812-4433-2211',
    licensePlate: 'B 9055 TKN',
    startTime: `${DAY_MINUS_3_STR}T13:00:00`,
    endTime: `${DAY_MINUS_3_STR}T16:00:00`,
    durationMinutes: 180,
    status: 'DONE',
    remarks: 'Selesai',
    createdAt: `${DAY_MINUS_3_STR}T07:30:00`,
  },
  {
    id: 'bk-m3-03',
    bookingCode: `SLOT-${DAY_MINUS_3_STR.replace(/-/g, '')}-D2-01`,
    poId: 'po-105',
    poNumber: 'PO-2026-08105',
    supplierName: 'PT Plastik Raya Sejahtera',
    itemDescription: 'Resin Granules',
    qty: 1000,
    unit: 'BAG',
    dockId: 'dock-2',
    dockName: 'Dock 02 (General Bay B)',
    vehicleId: 'veh-fuso',
    vehicleName: 'Fuso',
    vehicleCode: 'FUSO',
    driverName: 'Joko Widodo',
    driverPhone: '0812-5566-7788',
    licensePlate: 'B 9118 CD',
    startTime: `${DAY_MINUS_3_STR}T10:00:00`,
    endTime: `${DAY_MINUS_3_STR}T12:00:00`,
    durationMinutes: 120,
    status: 'DONE',
    remarks: 'Selesai',
    createdAt: `${DAY_MINUS_3_STR}T08:00:00`,
  },

  // --- TOMORROW BOOKINGS (DAY +1) ---
  {
    id: 'bk-p1-01',
    bookingCode: `SLOT-${TOMORROW_STR.replace(/-/g, '')}-D4-01`,
    poId: 'po-106',
    poNumber: 'PO-2026-08106',
    supplierName: 'PT Aneka Kimia Sentosa',
    itemDescription: 'Caustic Soda Flakes',
    qty: 500,
    unit: 'DRUM',
    dockId: 'dock-4',
    dockName: 'Dock 04 (Bay Tangki / Isotank)',
    vehicleId: 'veh-isotank',
    vehicleName: 'Isotank / Tangki Cair',
    vehicleCode: 'ISOTANK',
    driverName: 'Supriyanto',
    driverPhone: '0813-7766-5544',
    licensePlate: 'B 9234 TKP',
    startTime: `${TOMORROW_STR}T08:30:00`,
    endTime: `${TOMORROW_STR}T11:30:00`,
    durationMinutes: 180,
    status: 'BOOKED',
    remarks: 'Jadwal slot besok pagi',
    createdAt: `${TODAY_STR}T09:00:00`,
  },
  {
    id: 'bk-p1-02',
    bookingCode: `SLOT-${TOMORROW_STR.replace(/-/g, '')}-D1-01`,
    poId: 'po-101',
    poNumber: 'PO-2026-08101',
    supplierName: 'PT Sumber Logistik Prima',
    itemDescription: 'Cardboard Box Packaging',
    qty: 4500,
    unit: 'PCS',
    dockId: 'dock-1',
    dockName: 'Dock 01 (General Bay A)',
    vehicleId: 'veh-wb10',
    vehicleName: 'Wingbox 10 Ton',
    vehicleCode: 'WB10',
    driverName: 'Denny Kurniawan',
    driverPhone: '0818-7788-9900',
    licensePlate: 'D 8831 AA',
    startTime: `${TOMORROW_STR}T10:00:00`,
    endTime: `${TOMORROW_STR}T12:00:00`,
    durationMinutes: 120,
    status: 'BOOKED',
    remarks: 'Siap kirim',
    createdAt: `${TODAY_STR}T09:30:00`,
  },
  {
    id: 'bk-p1-03',
    bookingCode: `SLOT-${TOMORROW_STR.replace(/-/g, '')}-D3-01`,
    poId: 'po-104',
    poNumber: 'PO-2026-08104',
    supplierName: 'PT Sumber Logistik Prima',
    itemDescription: 'Pallet Kayu Standar',
    qty: 400,
    unit: 'PALLET',
    dockId: 'dock-3',
    dockName: 'Dock 03 (Fast Pallet Bay)',
    vehicleId: 'veh-wb20',
    vehicleName: 'Wingbox 20 Ton',
    vehicleCode: 'WB20',
    driverName: 'Heri Kurnia',
    driverPhone: '0817-2233-4455',
    licensePlate: 'B 9555 WB',
    startTime: `${TOMORROW_STR}T13:00:00`,
    endTime: `${TOMORROW_STR}T16:00:00`,
    durationMinutes: 180,
    status: 'BOOKED',
    remarks: 'Slot terjadwal',
    createdAt: `${TODAY_STR}T09:45:00`,
  },

  // --- DAY +2 BOOKINGS ---
  {
    id: 'bk-p2-01',
    bookingCode: `SLOT-${DAY_PLUS_2_STR.replace(/-/g, '')}-D5-01`,
    poId: 'po-103',
    poNumber: 'PO-2026-08103',
    supplierName: 'PT Steel Indo Sukses',
    itemDescription: 'Steel Coil 1.2mm',
    qty: 24,
    unit: 'COIL',
    dockId: 'dock-5',
    dockName: 'Dock 05 (Container High Bay)',
    vehicleId: 'veh-container',
    vehicleName: 'Kontainer 20/40 ft',
    vehicleCode: 'CONT',
    driverName: 'Wahyu Hidayat',
    driverPhone: '0857-4455-6677',
    licensePlate: 'B 9912 CTX',
    startTime: `${DAY_PLUS_2_STR}T10:00:00`,
    endTime: `${DAY_PLUS_2_STR}T14:00:00`,
    durationMinutes: 240,
    status: 'BOOKED',
    remarks: 'Unloading kontainer steel coil',
    createdAt: `${TODAY_STR}T10:00:00`,
  },
  {
    id: 'bk-p2-02',
    bookingCode: `SLOT-${DAY_PLUS_2_STR.replace(/-/g, '')}-D4-01`,
    poId: 'po-102',
    poNumber: 'PO-2026-08102',
    supplierName: 'PT Kimia Indah Perkasa',
    itemDescription: 'Liquid Solvents',
    qty: 18000,
    unit: 'LITER',
    dockId: 'dock-4',
    dockName: 'Dock 04 (Bay Tangki / Isotank)',
    vehicleId: 'veh-isotank',
    vehicleName: 'Isotank / Tangki Cair',
    vehicleCode: 'ISOTANK',
    driverName: 'Bambang Irawan',
    driverPhone: '0813-1122-3344',
    licensePlate: 'B 9088 TKL',
    startTime: `${DAY_PLUS_2_STR}T11:00:00`,
    endTime: `${DAY_PLUS_2_STR}T14:00:00`,
    durationMinutes: 180,
    status: 'BOOKED',
    remarks: 'Transfer tangki T-04',
    createdAt: `${TODAY_STR}T10:15:00`,
  },
  {
    id: 'bk-p2-03',
    bookingCode: `SLOT-${DAY_PLUS_2_STR.replace(/-/g, '')}-D2-01`,
    poId: 'po-105',
    poNumber: 'PO-2026-08105',
    supplierName: 'PT Plastik Raya Sejahtera',
    itemDescription: 'Resin Granules',
    qty: 1200,
    unit: 'BAG',
    dockId: 'dock-2',
    dockName: 'Dock 02 (General Bay B)',
    vehicleId: 'veh-cdd',
    vehicleName: 'Double Engkel (CDD)',
    vehicleCode: 'CDD',
    driverName: 'Agus Salim',
    driverPhone: '0852-1122-4455',
    licensePlate: 'B 9382 UQ',
    startTime: `${DAY_PLUS_2_STR}T14:30:00`,
    endTime: `${DAY_PLUS_2_STR}T16:00:00`,
    durationMinutes: 90,
    status: 'BOOKED',
    remarks: 'Ready delivery',
    createdAt: `${TODAY_STR}T10:30:00`,
  },
];

